### ISSUE TITLE
After running suspend/unsuspend, there is an exception

### ISSUE THREAD

**Issue by liorfranko** [SupersonicAds/spotcli#17]
**Describe the bug**
After running suspend/unsuspend on any scenario.
The groups got suspended or unsuspended, but the following exception is thrown:
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ spotcli/cli.py:375 in <module>                                                                   │
│                                                                                                  │
│   372                                                                                            │
│   373                                                                                            │
│   374 if __name__ == "__main__":                                                                 │
│ ❱ 375 │   main()                                                                                 │
│                                                                                                  │
│ /Users/lior.franko/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py:829 in        │
│ __call__                                                                                         │
│                                                                                                  │
│    826 │                                                                                         │
│    827 │   def __call__(self, *args, **kwargs):                                                  │
│    828 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱  829 │   │   return self.main(*args, **kwargs)                                                 │
│    830                                                                                           │
│    831                                                                                           │
│    832 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /Users/lior.franko/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py:782 in main   │
│                                                                                                  │
│    779 │   │   try:                                                                              │
│    780 │   │   │   try:                                                                          │
│    781 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱  782 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│    783 │   │   │   │   │   if not standalone_mode:                                               │
│    784 │   │   │   │   │   │   return rv                                                         │
│    785 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /Users/lior.franko/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py:1259 in       │
│ invoke                                                                                           │
│                                                                                                  │
│   1256 │   │   │   │   Command.invoke(self, ctx)                                                 │
│   1257 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1258 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1259 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1260 │   │                                                                                     │
│   1261 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1262 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /Users/lior.franko/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py:1066 in       │
│ invoke                                                                                           │
│                                                                                                  │
│   1063 │   │   """                                                                               │
│   1064 │   │   _maybe_show_deprecated_notice(self)                                               │
│   1065 │   │   if self.callback is not None:                                                     │
│ ❱ 1066 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1067                                                                                           │
│   1068                                                                                           │
│   1069 class MultiCommand(Command):                                                              │
│                                                                                                  │
│ /Users/lior.franko/.pyenv/versions/3.7.7/lib/python3.7/site-packages/click/core.py:610 in invoke │
│                                                                                                  │
│    607 │   │   args = args[2:]                                                                   │
│    608 │   │   with augment_usage_errors(self):                                                  │
│    609 │   │   │   with ctx:                                                                     │
│ ❱  610 │   │   │   │   return callback(*args, **kwargs)                                          │
│    611 │                                                                                         │
│    612 │   def forward(*args, **kwargs):  # noqa: B902                                           │
│    613 │   │   """Similar to :meth:`invoke` but fills in default keyword                         │
│                                                                                                  │
│ spotcli/cli.py:137 in run                                                                        │
│                                                                                                  │
│   134 │   │   console.print("\n")                                                                │
│   135 │   auto_approve or click.confirm("Continue?", abort=True)                                 │
│   136 │   t_start = time.time()                                                                  │
│ ❱ 137 │   s.run()                                                                                │
│   138 │   t_end = time.time()                                                                    │
│   139 │   duration = t_end - t_start                                                             │
│   140 │   console.print(                                                                         │
│                                                                                                  │
│ /Users/lior.franko/Repos/spotcli/spotcli/configuration/tasks.py:282 in run                       │
│                                                                                                  │
│   279 │   def run(self):                                                                         │
│   280 │   │   results = []                                                                       │
│   281 │   │   for task in self.tasks:                                                            │
│ ❱ 282 │   │   │   results.extend(task.run())                                                     │
│   283 │   │   return results                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

TypeError: 'NoneType' object is not iterable
**To Reproduce**
1. Run command 'spotcli run unsuspend-is'
2. See error

**Expected behavior**
No error

**Console output**
The above exception

**Configurations**
If applicable, add all existing configs.

**System (please complete the following information):**
 - OS: [e.g. macOS 11.0.0, Ubuntu 18.04]
 - Python version [e.g. 3.8.5]
 - Python installation source [e.g. system, apt, homebrew, pyenv]

**Additional info**
Add any other info about the problem here.

**Comment by zerodayyy** [comment]
This was fixed some time ago
